<?php

return [
1 => ['A_scale'=>'G','B_scale'=>'E','A'=>'Saya seorang pekerja giat','B'=>'Saya Bukan Seorang Pemurung'],
2 => ['A_scale'=>'A','B_scale'=>'N','A'=>'Saya suka bekerja lebih baik dari yang lain','B'=>'Saya melakukan pekerjaan hingga tuntas'],
3 => ['A_scale'=>'P','B_scale'=>'A','A'=>'Saya suka memberi orang petunjuk bagaimana melakukan sesuatu.','B'=>'Saya senang memberitahukan orang apa yang harus dikerjakan'],
4 => ['A_scale'=>'X','B_scale'=>'P','A'=>'Saya suka melakukan atau mengatakan hal-hal lucu.','B'=>'Saya senang memberitahukan orang apa yang harus dikerjakan'],
5 => ['A_scale'=>'B','B_scale'=>'X','A'=>'Saya suka menggabungkan diri dalam kelompok','B'=>'Saya ingin diperhatikan dalam kelompok.'],
6 => ['A_scale'=>'O','B_scale'=>'B','A'=>'Saya suka Menjalin persahabatan','B'=>'Saya suka menggabungkan diri dalam suatu kelompok'],
7 => ['A_scale'=>'Z','B_scale'=>'O','A'=>'Jika saya rasa perlu, saya bisa cepat menyesuaikan diri','B'=>'Saya berusaha Menjalin persahabatan'],
8 => ['A_scale'=>'K','B_scale'=>'Z','A'=>'Saya akan membalas jika saya di sakiti','B'=>'Saya suka melakukan hal-hal baru dan berbeda'],
9 => ['A_scale'=>'F','B_scale'=>'K','A'=>'Saya ingin atasan menyukai saya','B'=>'Saya suka memberitahukan orang jika mereka bersalah.'],
10 => ['A_scale'=>'W','B_scale'=>'F','A'=>'Saya suka mengikuti petunjuk yang di berikan kepada saya','B'=>'Saya suka membuat atasan senang'],

11 => ['A_scale'=>'G','B_scale'=>'C','A'=>'Saya berusaha keras sekali','B'=>'Saya seorang yang rapih'],
12 => ['A_scale'=>'L','B_scale'=>'E','A'=>'Saya dapat membuat orang melakukan apa yang saya inginkan','B'=>'Saya tidak mudah marah.'],
13 => ['A_scale'=>'P','B_scale'=>'N','A'=>'Saya suka memberitahu kelompok apa yang harus mereka kerjakan.','B'=>'Saya selalu melakukan pekerjaan sampai tuntas.'],
14 => ['A_scale'=>'X','B_scale'=>'A','A'=>'Saya ingin menjadi orang yang menarik dan mengasyikan.','B'=>'Saya ingin menjadi orang yang sangat berhasil'],
15 => ['A_scale'=>'B','B_scale'=>'P','A'=>'Saya ingin dapat menyesuaikan diri dengan kelompok-kelompok','B'=>'Saya suka membantu orang mengambil keputusan'],
16 => ['A_scale'=>'O','B_scale'=>'X','A'=>'Saya cemas bila seseorang tidak menyukai saya','B'=>'Saya suka orang memperhatikan saya'],
17 => ['A_scale'=>'Z','B_scale'=>'B','A'=>'Saya suka mencoba hal-hal baru','B'=>'Saya lebih suka bekerja sama daripada bekerja Sendiri'],
18 => ['A_scale'=>'K','B_scale'=>'O','A'=>'Kadang-kadang saya menyalahkan orang lain jika ada yang tidak beres.','B'=>'Saya merasa terganggu bila ada yang tidak menyukai saya.'],
19 => ['A_scale'=>'F','B_scale'=>'Z','A'=>'Saya suka menyenangkan atasan','B'=>'Saya suka mencoba pekerjaan - pekerjaan yang baru dan berbeda.'],
20 => ['A_scale'=>'W','B_scale'=>'K','A'=>'Saya menyukai petunjuk-petujuk yang rinci dalam menyelesaikan pekerjaan','B'=>'Akan saya katakan kepada orang-orang yang bersangkutan bila mereka menjengkelkan saya'],

21 => ['A_scale'=>'G','B_scale'=>'D','A'=>'Saya selalu berusaha keras','B'=>'Saya suka Melaksanakan Setiap langkah dengan hati-hati'],
22 => ['A_scale'=>'L','B_scale'=>'C','A'=>'Saya akan menjadi seorang pemimpin yang baik','B'=>'Saya dapat mengorganisir suatu pekerjaan dengan baik.'],
23 => ['A_scale'=>'I','B_scale'=>'E','A'=>'saya mudah tersinggung','B'=>'Saya lambat dalam membuat keputusan'],
24 => ['A_scale'=>'X','B_scale'=>'N','A'=>'Saya suka mengerjakan beberapa pekerjaan sekaligus','B'=>'Bila saya dalam kelompok, saya lebih sering sebagai pendengar.'],
25 => ['A_scale'=>'B','B_scale'=>'A','A'=>'Saya sangat senang bila mendapat undangan','B'=>'Saya ingin lebih baik dari yang lain dalam mengerjakan sesuatu.'],
26 => ['A_scale'=>'O','B_scale'=>'P','A'=>'Saya suka Menjalin persahabatan','B'=>'Saya suka menasehati orang lain'],
27 => ['A_scale'=>'Z','B_scale'=>'X','A'=>'Saya suka melakukan hal-hal baru dan berbeda','B'=>'Saya suka memberitahu bagaimana saya berhasil dalam melakukan sesuatu'],
28 => ['A_scale'=>'K','B_scale'=>'B','A'=>'Bila pendapat saya benar, saya akan pertahankan','B'=>'Saya ingin diterima dan diakui dalam kelompok'],
29 => ['A_scale'=>'F','B_scale'=>'O','A'=>'Saya tak mau menjadi lain dari yang lain','B'=>'Saya berusaha dekat dengan orang-orang'],
30 => ['A_scale'=>'W','B_scale'=>'Z','A'=>'Saya senang memberitahu orang bagaimana melakukan suatu pekerjaan','B'=>'Saya berusaha dekat dengan orang-orang'],

31 => ['A_scale'=>'G','B_scale'=>'R','A'=>'Saya bekerja keras','B'=>'Saya banyak berfikir dan membuat perencanaan'],
32 => ['A_scale'=>'L','B_scale'=>'D','A'=>'Saya memimpin kelompok','B'=>'Saya tertarik dengan hal-hal yang lebih detail'],
33 => ['A_scale'=>'I','B_scale'=>'C','A'=>'Saya mengambil Keputusan dengan mudah dan cepat','B'=>'Saya menyimpan barang-barang dengan rapih dan teratur'],
34 => ['A_scale'=>'T','B_scale'=>'E','A'=>'Saya melakukan pekerjaan dengan cepat','B'=>'Saya tidak sering marah atau sedih'],
35 => ['A_scale'=>'B','B_scale'=>'N','A'=>'Saya ingin menjadi bagian dari kelompok','B'=>'Saya hanya ingin melakukan pekerjaan pada satu waktu'],
36 => ['A_scale'=>'O','B_scale'=>'A','A'=>'Saya berusaha Menjalin persahabatan','B'=>'Saya berusaha keras menjadi yang terbaik'],
37 => ['A_scale'=>'Z','B_scale'=>'P','A'=>'Saya suka mode terbaru untuk pakaian','B'=>'Saya suka di beri tanggungjawab.'],
38 => ['A_scale'=>'K','B_scale'=>'X','A'=>'Saya menyukai perdebatan','B'=>'Saya senang mendapat perhatian'],
39 => ['A_scale'=>'F','B_scale'=>'B','A'=>'Saya suka menyenangkan atasan','B'=>'Saya tertarik menjadi bagian dalam kelompok'],
40 => ['A_scale'=>'W','B_scale'=>'O','A'=>'Saya sangat memperhatikan peraturan','B'=>'Saya ingin orang mengenal saya dengan baik'],

41 => ['A_scale'=>'G','B_scale'=>'S','A'=>'Saya berusaha keras sekali','B'=>'Saya sangat ramah'],
42 => ['A_scale'=>'L','B_scale'=>'R','A'=>'Orang berpendapat saya memimpin dengan baik','B'=>'Saya berfikir lama dan berhati - hati'],
43 => ['A_scale'=>'I','B_scale'=>'D','A'=>'Bila ada kesempatan, saya akan memanfaatkan nya.','B'=>'Saya senang menangani hal-hal kecil'],
44 => ['A_scale'=>'T','B_scale'=>'C','A'=>'Orang berpendapat bahwa saya bekerja cepat','B'=>'Orang berpendapat bahwa saya rapi dan teratur'],
45 => ['A_scale'=>'V','B_scale'=>'E','A'=>'Saya senang mengikuti pertandingan dan berolahraga.','B'=>'Saya memiliki kepribadian yang menyenangkan'],
46 => ['A_scale'=>'O','B_scale'=>'N','A'=>'Saya senang jika orang dekat dan bersahabat dengan saya','B'=>'Saya selalu berusaha menyelesaikan sesuatu yang telah saya mulai'],
47 => ['A_scale'=>'Z','B_scale'=>'A','A'=>'Saya senang bereksperimen dan mencoba hal-hal baru','B'=>'Saya suka mengerjakan pekerjaan yang sulit-sulit'],
48 => ['A_scale'=>'K','B_scale'=>'P','A'=>'Saya suka diperlakukan dengan adil','B'=>'Saya suka memberitahu orang lain bagaimana Melaksanakan sesuatu.'],
49 => ['A_scale'=>'F','B_scale'=>'X','A'=>'Saya suka melakukan apa yang diharapkan orang dari saya.','B'=>'Saya suka jika orang perduli terhadap saya'],
50 => ['A_scale'=>'W','B_scale'=>'B','A'=>'Saya suka diterangkan tugas saya sedetail-detailnya','B'=>'Saya senang berada bersama orang-orang'],

51 => ['A_scale'=>'G','B_scale'=>'V','A'=>'Saya selalu berusaha menyelesaikan pekerjaan dengan sempurna.','B'=>'Orang mengatakan bahwa saya hampir-hampir tidak pernah lelah.'],
52 => ['A_scale'=>'L','B_scale'=>'S','A'=>'Saya tipe pemimpin','B'=>'Saya mudah bergaul'],
53 => ['A_scale'=>'I','B_scale'=>'R','A'=>'Saya gunakan kesempatan','B'=>'Saya banyak sekali berfikir'],
54 => ['A_scale'=>'T','B_scale'=>'D','A'=>'Saya bekerja dengan tempo yang tinggi dan mantap','B'=>'Saya senang menangani detail suatu pekerjaan'],
55 => ['A_scale'=>'V','B_scale'=>'C','A'=>'Saya memiliki banyak tenaga untuk kegiatan dan berolah raga.','B'=>'Saya mengatur dan menyimpan barang dengan teratur dan rapi.'],
56 => ['A_scale'=>'S','B_scale'=>'E','A'=>'Saya dapat bergaul baik dengan semua orang','B'=>'Saya orang yang berwatak tenang'],
57 => ['A_scale'=>'Z','B_scale'=>'N','A'=>'Saya ingin bertemu dengan orang-orang baru dan melakukan hal-hal baru.','B'=>'Saya selalu ingin menyelesaikan pekerjaan yang telah saya mulai'],
58 => ['A_scale'=>'K','B_scale'=>'A','A'=>'Saya biasanya mempertahankan pendapat yang saya yakini.','B'=>'Saya biasanya suka bekerja keras.'],
59 => ['A_scale'=>'F','B_scale'=>'P','A'=>'Saya menyambut baik saran-saran dari orang yang saya kagumi.','B'=>'Saya suka bertanggung jawab terhadap orang lain'],
60 => ['A_scale'=>'W','B_scale'=>'X','A'=>'Saya membiarkan diri saya dipengaruhi dengan kuat oleh orang lain','B'=>'Saya senang bila memperoleh banyak perhatian'],

61 => ['A_scale'=>'G','B_scale'=>'T','A'=>'Biasanya saya bekerja keras sekali.','B'=>'Biasanya saya bekerja cepat'],
62 => ['A_scale'=>'L','B_scale'=>'V','A'=>'Apabila saya bicara, kelompok diam dan mendengarkan','B'=>'Saya trampil menggunakan perkakas'],
63 => ['A_scale'=>'I','B_scale'=>'S','A'=>'Saya lambat dalam membuat persahabatan','B'=>'Saya lambat dalam mengambil Keputusan'],
64 => ['A_scale'=>'T','B_scale'=>'R','A'=>'Biasanya saya makan dengan cepat','B'=>'Saya suka membaca'],
65 => ['A_scale'=>'V','B_scale'=>'D','A'=>'Saya suka pekerjaan Dimana saya banyak bergerak','B'=>'Saya suka pekerjaan yang harus dilaksanakan dengan hati-hati'],
66 => ['A_scale'=>'S','B_scale'=>'C','A'=>'Saya mudah membuat sebanyak mungkin teman','B'=>'Saya mudah menemukan kembali barang-barang yang saya simpan'],
67 => ['A_scale'=>'R','B_scale'=>'E','A'=>'Saya membuat rencana jauh-jauh sebelumnya','B'=>'Saya selalu menyenangkan'],
68 => ['A_scale'=>'K','B_scale'=>'N','A'=>'Saya menjunjung tinggi nama baik saya','B'=>'Saya terus menekuni suatu masalah sampai tuntas'],
69 => ['A_scale'=>'F','B_scale'=>'A','A'=>'Saya suka menyenangkan orang-orang yang saya kagumi','B'=>'Saya ingin sukses'],
70 => ['A_scale'=>'W','B_scale'=>'P','A'=>'Saya suka orang lain mengambil Keputusan untuk kelompok','B'=>'Saya suka mengambil Keputusan untuk kelompok'],

71 => ['A_scale'=>'G','B_scale'=>'I','A'=>'Saya selalu berusaha keras','B'=>'Saya mengambil Keputusan secara cepat dan mudah'],
72 => ['A_scale'=>'L','B_scale'=>'T','A'=>'Kelompok biasanya melakukan apa yang saya inginkan','B'=>'Saya biasanya bekerja cepat-cepat'],
73 => ['A_scale'=>'I','B_scale'=>'V','A'=>'Saya sering merasa lelah','B'=>'Saya lambat dalam mengabil Keputusan'],
74 => ['A_scale'=>'T','B_scale'=>'S','A'=>'Saya bekerja cepat','B'=>'Saya mudah berteman'],
75 => ['A_scale'=>'V','B_scale'=>'R','A'=>'Saya biasanya mempunyai gairah dan tenaga','B'=>'Saya banyak menghabiskan waktu untuk berfikir'],
76 => ['A_scale'=>'S','B_scale'=>'D','A'=>'Saya sangat ramah terhadap orang','B'=>'Saya suka pekerjaan yang memerlukan ketelitian'],
77 => ['A_scale'=>'R','B_scale'=>'C','A'=>'Saya banyak berfikir dan membuat perencanaan','B'=>'Saya menyimpan sesuatu pada tempatnya'],
78 => ['A_scale'=>'D','B_scale'=>'E','A'=>'Saya suka pekerjaan yang menuntut perhatian terhadap hal detail.','B'=>'Saya tidak mudah marah'],
79 => ['A_scale'=>'F','B_scale'=>'N','A'=>'Saya suka menuruti orang yang saya kagumi','B'=>'Saya selalu menyelesaikan pekerjaan yang telah saya mulai'],
80 => ['A_scale'=>'W','B_scale'=>'A','A'=>'Saya suka petunjuk - petunjuk yang jelas','B'=>'Saya suka bekerja keras.'],

81 => ['A_scale'=>'G','B_scale'=>'L','A'=>'Saya mngejar apa yang saya inginkan','B'=>'Saya seorang pemimpin yang baik'],
82 => ['A_scale'=>'L','B_scale'=>'I','A'=>'Saya dapat membuat orang lain bekerja keras','B'=>'Saya adalah type orang yang tak kenal susah'],
83 => ['A_scale'=>'I','B_scale'=>'T','A'=>'Saya mengambil Keputusan dengan cepat','B'=>'Saya bicara dengan cepat'],
84 => ['A_scale'=>'T','B_scale'=>'V','A'=>'Rasanya saya bekerja secara tergesa-gesa','B'=>'Saya berolah raga secara teratur'],
85 => ['A_scale'=>'V','B_scale'=>'S','A'=>'saya tidak suka bertemu kebanyakan orang','B'=>'Saya cepat merasa lelah'],
86 => ['A_scale'=>'S','B_scale'=>'R','A'=>'Saya mempunyai banyak sekali teman','B'=>'Saya banyak menghabiskan waktu untuk berfikir'],
87 => ['A_scale'=>'R','B_scale'=>'D','A'=>'Saya suka bekerja dengan teori','B'=>'Saya suka menangani detail suatu pekerjaan'],
88 => ['A_scale'=>'D','B_scale'=>'C','A'=>'Saya suka menangani detail suatu pekerjaan','B'=>'Saya Suka mengorganisir pekerjaan saya'],
89 => ['A_scale'=>'E','B_scale'=>'C','A'=>'Saya menaruh barang pada tempatnya','B'=>'Saya selalu menyenangkan'],
90 => ['A_scale'=>'W','B_scale'=>'N','A'=>'Saya suka diberitahu apa yang perlu saya kerjakan','B'=>'Saya harus menyelesaikan pekerjaan yang telah saya mulai'],
];